#!/bin/bash

#$ -V 
#$ -cwd

name=$1
jobfile=$name.log
delscratch="true"
export basedir=$PWD


export scrdir="/scratch/${USER}"
export SCRATCH=$scrdir/${JOB_ID}

echo  ${JOB_ID}         > $jobfile
echo  ${USER}       >>  $jobfile
echo  ${HOSTNAME}   >>  $jobfile
echo  ${SCRATCH}     >>  $jobfile
echo  $basedir      >>  $jobfile
echo 'NSLOTS: '${NSLOTS}                >>  $jobfile   #NSLOTS


if [[ -d $SCRATCH ]];then
   echo "Job direcory $SCRDIR already exist!"
   echo "Exiting..."
   exit 1
else
   mkdir ${SCRATCH}
   cp -p * $SCRATCH/.

fi

cd $SCRATCH
 
function clean_scratch {
   echo "Job stopped after qdel ${JOB_ID}">> $jobfile
   echo "Copying current data back to $basedir/">> $jobfile
   cp -pr * $basedir/.
   cd ../
   rm -r $SCRATCH
   exit 1
}
trap clean_scratch SIGUSR2  #if qdel JOBID then copy current data to basedir



#required libraries for OCTOPUS
export octopuslibs=/home/chalabaj/prog/octopus/Octopus_environment.sh
source $octopuslibs

if [[ $nproc -gt "1" ]]; then
#$ -pe mpi $nproc
export OMP_NUM_THREADS=1  
mpirun -np ${NSLOTS} octopus > $name.out
else
octopus > $name.out
fi

cp -pr * $basedir/.

echo 'Normal termination of:' ${JOB_ID} >> $jobfile

if [[ $delscratch -eq "true" ]];then
  cd ../
  rm -r $SCRATCH
fi
