#!/bin/bash

#$ -V 
#$ -cwd

name=$1
jobfile=$name.log
delscratch='true'
export homedir=$PWD


export scrdir="/scratch/${USER}"
export SCRATCH=$scrdir/${JOB_ID}

echo 'Job ID in que: ' ${JOB_ID}         > $jobfile
echo 'Job submitted by: ' ${USER}       >>  $jobfile
echo 'Job is running at: '${HOSTNAME}   >>  $jobfile
echo 'Folder on sratch: '${SCRATCH}     >>  $jobfile
echo 'Base directory:' $homedir      >>  $jobfile
echo 'NSLOTS: '${NSLOTS}                >>  $jobfile   #NSLOTS
echo 'Delete scratch after finished job:' $delscratch >> $jobfile
trap "qdel ${JOB_ID}" clean_scratch

if [[ -d $SCRATCH ]];then
   echo "Job direcory $SCRDIR already exist!"
   echo "Exiting..."
   exit 1
else
   mkdir ${SCRATCH}
   cp -p * $SCRATCH/.
fi

cd $SCRATCH
#required libraries for OCTOPUS
export octopuslibs=/home/chalabaj/prog/octopus/Octopus_environment.sh
source $octopuslibs

if [[ $nproc -gt "1" ]]; then
#$ -pe mpi $nproc
export OMP_NUM_THREADS=1  
mpirun -np ${NSLOTS} octopus > $name.out
else
octopus > $name.out
fi


function clean_scratch {
   echo "Job stopped after qdel ${JOB_ID}">>$jobfile
   echo "Copying current data back to $homedir.">> $jobfile
   cp -pr * $homedir/.
   rm -r $SCRATCH
   exit
}

cp -pr * $homedir/.

if [[ $delscratch -eq "true" ]];then
  rm -r $SCRATCH
fi

echo 'Normal termination of:' ${JOB_ID} >> $jobfile